services:
  server:
    environment:
      LLM: llama3.2
      PORT: 8080
      OLLAMA_URL: http://llm:11434
      QDRANT_URL: http://db:6333
      QDRANT_COLLECTION: test
      NEXT_TELEMETRY_DISABLED: 1
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
  llm:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
  db:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - ./storage:/qdrant/storage
